services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  # prisma-studio:
  #   image: node:lts-alpine3.17
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #   command: npx prisma studio --port 5555 --browser none
  #   env_file:
  #     - .env
  #   ports:
  #     - "5555:5555"
  #   networks:
  #     - my_network
  #   depends_on:
  #     - postgres

  # backend:
  #   container_name: backend
  #   restart: always
  #   depends_on:
  #     - postgres
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     PORT: ${PORT}
  #     NODE_ENV: ${NODE_ENV}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #     DB_URL: ${DB_URL}
  #     CORS_ORIGIN: ${CORS_ORIGIN}
  #   networks:
  #     - my_network
  #   ports:
  #     - ${PORT}:${PORT}

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
