services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  # backend:
  #   container_name: backend
  #   restart: always
  #   depends_on:
  #     - postgres
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     PORT: ${PORT}
  #     NODE_ENV: ${NODE_ENV}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     DB_URL: ${DB_URL}
  #     CORS_ORIGIN: ${CORS_ORIGIN}
  #   networks:
  #     - my_network
  #   ports:
  #     - ${PORT}:${PORT}

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
